sudo: false
language: node_js
node_js:
- '4'
env:
  global:
  - SAUCE_USERNAME=opbeat
  - SAUCE_ACCESS_KEY=de42e589-1450-41a2-8a44-90aa00c15168
  matrix:
  - MODE=saucelabs"
cache:
  directories:
  - node_modules
addons:
  firefox: '38.0'
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
notifications:
  slack:
    secure: VH+rtc1Zv/FEGk17sF7rxNcoz+JbG1KjU5myG78/AFBQBuWPhgO8UEEl1ca6zjEi3osw4TUlkF23kxWZZPZevUrojN4oUe7lCd0lLrlitG7uAmGoB0co4lrREdYO7WvUQEG51iMwIWVF0clDwiJf7VZ7Epgxy3vxNiNp1Cm8CRznQt9q06FWflhSK78sA2gjrTs3nYfMWkJPv75HwMpkMNISrk/5PGK/kBrbvTl8wDZ3iocUT66vziH3GVTutSuaW8VftahDv4PoQ3Ob+ZMKYd8j/PKzGCmQcv2bRHXaZQvK/Kdyia5HeYrwT17pzdThgIADfGFe5BLhtqoH+wFgMswhNmvce6TchZ5rsBMi2VFpF4wkXYGcyDw5mN8x7dEKo15aKCyNRKNv9UzpmgYYnuNOLi/n7mVze9yULCLgo3Zm7QSoRoYtLVRus2yjnZCVjoGfnztpyYQfm81bGc4HI+XDJ0fAoKXMa8WfMIsxOFHYNfrNMyRV5MT/d3r6yXPuRJV0drIf9TPX+cLBbFlA0DueSQraRra5jNjJOp9hTC1Iz6MdJIptEc5hZxYsVrNaTsGY2N19gpZ8sdmheIUGI4zfR7tSyvcIeR2+ywjBxMnQTl8d8H3+4Gac0rf+m7NeFgoUI1HldQ3riKTp0rffbjKgVjb0dPxXG0C+ieEwPpQ=
